"""Generate the ML file-usage index from Python and notebook imports.

Run from any directory; --check exits nonzero when the committed index is stale.
This reads source syntax only and never imports the scientific stack.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import json
import os
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PACKAGE = REPO / "src/satellites/ml_classification"
PREFIX = "satellites.ml_classification"
LEGACY = {"to_delete"}


def module_name(path: Path) -> str:
    parts = list(path.relative_to(REPO / "src").with_suffix("").parts)
    if parts[:3] == ["satellites", "ml_classification", "to_delete"]:
        # The package's temporary search path exposes these under their old names.
        parts.pop(2)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def imports_from(source: str, package: str = "") -> set[str]:
    """Read explicit imports, including function-local imports and literal aliases."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return set()
    targets = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            targets.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            target = node.module or ""
            if node.level:
                if not package:
                    continue
                target = importlib.util.resolve_name("." * node.level + target, package)
            targets.add(target)
            targets.update(target + "." + alias.name for alias in node.names)
        elif isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute) and node.func.attr == "import_module":
            if node.args and isinstance(node.args[0], ast.Constant) and isinstance(node.args[0].value, str):
                targets.add(node.args[0].value)
    return targets


def link(path: Path) -> str:
    target = Path(os.path.relpath(path, PACKAGE)).as_posix()
    label = path.relative_to(PACKAGE).as_posix() if path.is_relative_to(PACKAGE) else path.relative_to(REPO).as_posix()
    return f"[{label}]({target})"


def generate() -> str:
    files = sorted(path for path in PACKAGE.rglob("*.py") if "_archive" not in path.relative_to(PACKAGE).parts)
    modules = {module_name(path): path for path in files}
    consumers: dict[str, set[Path]] = defaultdict(set)
    for directory in ("src", "tests", "scripts"):
        for path in (REPO / directory).rglob("*.py"):
            if path.is_relative_to(PACKAGE / "to_delete" / "_archive"):
                continue
            source = path.read_text(encoding="utf-8-sig")
            package = module_name(path) if path.is_relative_to(REPO / "src") else ""
            if path.name != "__init__.py":
                package = package.rpartition(".")[0]
            for target in imports_from(source, package):
                if target in modules and modules[target] != path:
                    consumers[target].add(path)
    for path in (REPO / "notebooks").rglob("*.ipynb"):
        notebook = json.loads(path.read_text(encoding="utf-8-sig"))
        for cell in notebook.get("cells", []):
            if cell.get("cell_type") == "code":
                for target in imports_from("".join(cell.get("source", []))):
                    if target in modules:
                        consumers[target].add(path)

    lines = [
        "# ML file usage",
        "",
        "Generated by `python scripts/generate_ml_code_map.py`. Do not edit this file manually.",
        "",
        "Start with [README.md](README.md) for execution order and artifact producers/consumers.",
        "",
        "This index lists direct, statically discoverable importers, including tests, notebooks,",
        "function-local imports, and literal compatibility aliases. It is not a runtime call graph.",
        "Inherited step methods are called by `pipeline.py`; shared helper calls are visible in",
        "each step's explicit imports. Pickle/joblib can resolve historical class paths without",
        "a source import. Optional dependencies and external notebooks may add other consumers.",
        "",
    ]
    for legacy, title in ((False, "Maintained implementations"), (True, "Compatibility modules awaiting deletion")):
        lines += [f"## {title}", "", "| File | Responsibility | Direct importers |", "| --- | --- | --- |"]
        for path in files:
            relative = path.relative_to(PACKAGE)
            if (relative.parts[0] in LEGACY) != legacy:
                continue
            tree = ast.parse(path.read_text(encoding="utf-8-sig"))
            description = (ast.get_docstring(tree) or "Package marker.").splitlines()[0].replace("|", "\\|")
            users = consumers[module_name(path)]
            imported_by = "<br>".join(link(p) for p in sorted(users))
            if not imported_by:
                imported_by = (
                    "Package initialization"
                    if path.name == "__init__.py"
                    else "No static importer; public/CLI or compatibility entry point"
                )
            lines.append(f"| {link(path)} | {description} | {imported_by} |")
        lines.append("")
    lines += [
        "## Historical namespaces",
        "",
        "The small packages under `src/_compat/ml_classification*` forward historical imports",
        "to this package. During testing, `to_delete/` supplies the old `core`, `steps`,",
        "`reporting`, and `visuals` names through an optional package search path.",
        "`to_delete/shared/` preserves former flat shared-module names, including modeling context and reports.",
        "Maintained code uses the numbered step packages and `shared/` directly.",
        "The source snapshots in `to_delete/_archive/` are recovery copies, excluded from this index.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = PACKAGE / "FILE_USAGE.md"
    rendered = generate()
    if args.check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("ML file-usage index is stale: run python scripts/generate_ml_code_map.py")
        print("ML file-usage index is current.")
    else:
        output.write_text(rendered, encoding="utf-8")
        print(output)


if __name__ == "__main__":
    main()
